package com.gdut.imis.campus.model;

public class Enterprise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.id
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.credit_code
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.password
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.type
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.company
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.establish_time
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String establishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.hr_name
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String hrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.phone
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.status
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.tag
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.email
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.address
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.avatar_url
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.gmt_create
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.gmt_modified
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.bio
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    private String bio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.id
     *
     * @return the value of enterprise.id
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.id
     *
     * @param id the value for enterprise.id
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.credit_code
     *
     * @return the value of enterprise.credit_code
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.credit_code
     *
     * @param creditCode the value for enterprise.credit_code
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.password
     *
     * @return the value of enterprise.password
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.password
     *
     * @param password the value for enterprise.password
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.type
     *
     * @return the value of enterprise.type
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.type
     *
     * @param type the value for enterprise.type
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.company
     *
     * @return the value of enterprise.company
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.company
     *
     * @param company the value for enterprise.company
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.establish_time
     *
     * @return the value of enterprise.establish_time
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getEstablishTime() {
        return establishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.establish_time
     *
     * @param establishTime the value for enterprise.establish_time
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setEstablishTime(String establishTime) {
        this.establishTime = establishTime == null ? null : establishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.hr_name
     *
     * @return the value of enterprise.hr_name
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getHrName() {
        return hrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.hr_name
     *
     * @param hrName the value for enterprise.hr_name
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setHrName(String hrName) {
        this.hrName = hrName == null ? null : hrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.phone
     *
     * @return the value of enterprise.phone
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.phone
     *
     * @param phone the value for enterprise.phone
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.status
     *
     * @return the value of enterprise.status
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.status
     *
     * @param status the value for enterprise.status
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.tag
     *
     * @return the value of enterprise.tag
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.tag
     *
     * @param tag the value for enterprise.tag
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.email
     *
     * @return the value of enterprise.email
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.email
     *
     * @param email the value for enterprise.email
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.address
     *
     * @return the value of enterprise.address
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.address
     *
     * @param address the value for enterprise.address
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.avatar_url
     *
     * @return the value of enterprise.avatar_url
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.avatar_url
     *
     * @param avatarUrl the value for enterprise.avatar_url
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.gmt_create
     *
     * @return the value of enterprise.gmt_create
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.gmt_create
     *
     * @param gmtCreate the value for enterprise.gmt_create
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.gmt_modified
     *
     * @return the value of enterprise.gmt_modified
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.gmt_modified
     *
     * @param gmtModified the value for enterprise.gmt_modified
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.bio
     *
     * @return the value of enterprise.bio
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.bio
     *
     * @param bio the value for enterprise.bio
     *
     * @mbg.generated Thu Feb 27 14:48:31 CST 2020
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }
}