package com.gdut.imis.campus.model;

public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.id
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.name
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.degree
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.low_salary
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Integer lowSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.high_salary
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Integer highSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.view_count
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.status
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.gmt_create
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.gmt_modify
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Long gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.gmt_invalid
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String gmtInvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.enterprise_id
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.enterprise_name
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.enterprise_logo
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String enterpriseLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.type
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.work_days
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Integer workDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.province
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.city
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.district
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.daily_salary
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Integer dailySalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.id
     *
     * @return the value of job.id
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.id
     *
     * @param id the value for job.id
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.name
     *
     * @return the value of job.name
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.name
     *
     * @param name the value for job.name
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.degree
     *
     * @return the value of job.degree
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.degree
     *
     * @param degree the value for job.degree
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.low_salary
     *
     * @return the value of job.low_salary
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Integer getLowSalary() {
        return lowSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.low_salary
     *
     * @param lowSalary the value for job.low_salary
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setLowSalary(Integer lowSalary) {
        this.lowSalary = lowSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.high_salary
     *
     * @return the value of job.high_salary
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Integer getHighSalary() {
        return highSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.high_salary
     *
     * @param highSalary the value for job.high_salary
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setHighSalary(Integer highSalary) {
        this.highSalary = highSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.view_count
     *
     * @return the value of job.view_count
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.view_count
     *
     * @param viewCount the value for job.view_count
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.status
     *
     * @return the value of job.status
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.status
     *
     * @param status the value for job.status
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.gmt_create
     *
     * @return the value of job.gmt_create
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.gmt_create
     *
     * @param gmtCreate the value for job.gmt_create
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.gmt_modify
     *
     * @return the value of job.gmt_modify
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.gmt_modify
     *
     * @param gmtModify the value for job.gmt_modify
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.gmt_invalid
     *
     * @return the value of job.gmt_invalid
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getGmtInvalid() {
        return gmtInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.gmt_invalid
     *
     * @param gmtInvalid the value for job.gmt_invalid
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setGmtInvalid(String gmtInvalid) {
        this.gmtInvalid = gmtInvalid == null ? null : gmtInvalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.enterprise_id
     *
     * @return the value of job.enterprise_id
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.enterprise_id
     *
     * @param enterpriseId the value for job.enterprise_id
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.enterprise_name
     *
     * @return the value of job.enterprise_name
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.enterprise_name
     *
     * @param enterpriseName the value for job.enterprise_name
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.enterprise_logo
     *
     * @return the value of job.enterprise_logo
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getEnterpriseLogo() {
        return enterpriseLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.enterprise_logo
     *
     * @param enterpriseLogo the value for job.enterprise_logo
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setEnterpriseLogo(String enterpriseLogo) {
        this.enterpriseLogo = enterpriseLogo == null ? null : enterpriseLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.type
     *
     * @return the value of job.type
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.type
     *
     * @param type the value for job.type
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.work_days
     *
     * @return the value of job.work_days
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Integer getWorkDays() {
        return workDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.work_days
     *
     * @param workDays the value for job.work_days
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setWorkDays(Integer workDays) {
        this.workDays = workDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.province
     *
     * @return the value of job.province
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.province
     *
     * @param province the value for job.province
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.city
     *
     * @return the value of job.city
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.city
     *
     * @param city the value for job.city
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.district
     *
     * @return the value of job.district
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.district
     *
     * @param district the value for job.district
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.daily_salary
     *
     * @return the value of job.daily_salary
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Integer getDailySalary() {
        return dailySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.daily_salary
     *
     * @param dailySalary the value for job.daily_salary
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setDailySalary(Integer dailySalary) {
        this.dailySalary = dailySalary;
    }
}