package com.gdut.imis.campus.model;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.id
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_name
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.password
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.type
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_phone
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String mPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_email
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String mEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.m_address
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    private String mAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.id
     *
     * @return the value of manager.id
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.id
     *
     * @param id the value for manager.id
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_name
     *
     * @return the value of manager.m_name
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_name
     *
     * @param mName the value for manager.m_name
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.password
     *
     * @return the value of manager.password
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.password
     *
     * @param password the value for manager.password
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.type
     *
     * @return the value of manager.type
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.type
     *
     * @param type the value for manager.type
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_phone
     *
     * @return the value of manager.m_phone
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getmPhone() {
        return mPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_phone
     *
     * @param mPhone the value for manager.m_phone
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setmPhone(String mPhone) {
        this.mPhone = mPhone == null ? null : mPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_email
     *
     * @return the value of manager.m_email
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getmEmail() {
        return mEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_email
     *
     * @param mEmail the value for manager.m_email
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setmEmail(String mEmail) {
        this.mEmail = mEmail == null ? null : mEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.m_address
     *
     * @return the value of manager.m_address
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public String getmAddress() {
        return mAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.m_address
     *
     * @param mAddress the value for manager.m_address
     *
     * @mbg.generated Tue Apr 21 22:32:01 CST 2020
     */
    public void setmAddress(String mAddress) {
        this.mAddress = mAddress == null ? null : mAddress.trim();
    }
}